CREATE TABLE TB_EMPRESA (
    CNPJ VARCHAR(30) NOT NULL,
    RAZAO_SOCIAL VARCHAR(100),
    NOME_FANTASIA VARCHAR(60),
    ENDERECO VARCHAR(100),
    CEP VARCHAR(10),
    TELEFONE VARCHAR(30),
    IE VARCHAR(20),
    LOGOMARCA BLOB SUB_TYPE 0 SEGMENT SIZE 80)
